name: test_wintools
on:
  push: {tags:  ['v*'] } # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request: 

permissions:
  contents: write
  
jobs:
  test_windll_winhook:
    runs-on: windows-2019
    steps:
    - name: pull and init
      uses: actions/checkout@v3
      with: {submodules: true}
    
    - name: add msbuild to path
      uses: microsoft/setup-msbuild@v1.1
    
    - name: test target
      shell: cmd
      run: .\project\windll_winhook\test_msvc.bat

  test_windll_winpe:
    runs-on: windows-2019
    steps:
    - name: pull and init
      uses: actions/checkout@v3
      with: {submodules: true}
    
    - name: add msbuild to path
      uses: microsoft/setup-msbuild@v1.1
    
    - name: test target
      shell: cmd
      run: .\project\windll_winpe\test_msvc.bat